question_data = [
        {
            "category": "Entertainment: Video Games",
            "type": "boolean", "difficulty": "hard",
            "question": "The retail disc of Tony Hawk&#039;s Pro Skater 5 only comes with the tutorial.",
            "correct_answer": "True",
            "incorrect_answers": ["False"]
        },
        {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
         "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "History", "type": "boolean", "difficulty": "hard",
         "question": "The fourth funnel of the RMS Titanic was fake designed to make the ship look more powerful and symmetrical.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
         "question": "TF2: Sentry rocket damage falloff is calculated based on the distance between the sentry and the enemy, not the engineer and the enemy",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "Throughout the entirety of &quot;Dragon Ball Z&quot;, Goku only kills two characters: a miniboss named Yakon and Kid Buu.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
         "question": "The song &quot;Mystery Train&quot; was released by artist &quot;Little Junior&#039;s Blue Flames&quot; in 1953.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "hard",
         "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
         "question": "In Scandinavian languages, the letter &Aring; means river.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
    {"category": "Geography", "type": "boolean", "difficulty": "hard",
                                           "question": "Switzerland has four national languages, English being one of them.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "The character Plum from &quot;No Game No Life&quot; is a girl.", "correct_answer": "False",
         "incorrect_answers": ["True"]}]
